import type { IMatch, IMonth, IPlayer, IPlayerStats, ITeam } from './types';

export const STATS: Array<IPlayerStats> = [
  {
    id: '1',
    player_id: '1',
    match_id: '1',
    matches_played: 2,
    goals: 1,
    assists: 1,
    red_card: 0,
    yellow_card: 0,
    yellow_red_card: 0,
    minutes: 12,
    relevant_season: 2021,
  },
  {
    id: '2',
    player_id: '1',
    match_id: '1',
    matches_played: 4,
    goals: 10,
    assists: 5,
    red_card: 1,
    yellow_card: 2,
    yellow_red_card: 1,
    minutes: 36,
    relevant_season: 2022,
  },
  {
    id: '3',
    player_id: '1',
    match_id: '1',
    matches_played: 6,
    goals: 5,
    assists: 2,
    red_card: 1,
    yellow_card: 2,
    yellow_red_card: 1,
    minutes: 60,
    relevant_season: 2023,
  },
  {
    id: '2',
    player_id: '1',
    match_id: '1',
    matches_played: 10,
    goals: 10,
    assists: 5,
    red_card: 1,
    yellow_card: 2,
    yellow_red_card: 1,
    minutes: 95,
    relevant_season: 2024,
  },
];

export const PLAYERS: Array<IPlayer> = [
  {
    id: '1',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/arsa.JPG',
    player_number: '02',
    position: 'striker',
    age: '28',
    team: '1',
    is_current: true,
    background_story:
      'Тэрээр Архангай аймагийн уугуул ба 2020 оноос хойш Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '2',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/chinbaa.JPG',
    player_number: '99',
    position: 'striker',
    age: '28',
    team: '2',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '3',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/Dawka.JPG',
    player_number: '11',
    position: 'striker',
    age: '28',
    team: '1',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '4',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_1274.JPG',
    player_number: '33',
    position: 'striker',
    age: '28',
    team: '2',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '5',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_9035.JPG',
    player_number: '02',
    position: 'striker',
    age: '28',
    team: '1',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '6',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_9034.JPG',
    player_number: '99',
    position: 'striker',
    age: '28',
    team: '1',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '7',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_9033.JPG',
    player_number: '11',
    position: 'striker',
    age: '28',
    team: '2',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '8',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_9032.JPG',
    player_number: '33',
    position: 'striker',
    age: '28',
    team: '1',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '9',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_9031.JPG',
    player_number: '02',
    position: 'striker',
    age: '28',
    team: '2',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '10',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_9030.JPG',
    player_number: '99',
    position: 'striker',
    age: '28',
    team: '2',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '11',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_9029.JPG',
    player_number: '11',
    position: 'striker',
    age: '28',
    team: '1',
    is_current: true,
    background_story:
      'Тэрээр Архангай аймагийн уугуул ба 2020 оноос хойш Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
  {
    id: '12',
    first_name: 'Enkh-Uchral',
    last_name: 'Ganbat',
    date_of_birth: '1996/02/20',
    height: '180cm',
    weight: '70kg',
    img_url: '/assets/players/IMG_4968.JPG',
    player_number: '33',
    position: 'striker',
    age: '28',
    team: '2',
    is_current: true,
    background_story: 'Тэрээр Мазаалай клубд 4 жил довтлогчоор тоглож байгаа',
  },
];


export const MATCHES: IMatch[] = [
  {
    id: "1",
    created_at: "2024-08-13T10:00:00Z",
    home_id: "100",
    away_id: "200",
    season: "2024/25",
    match_type: "1",
    home_goals: "2",
    away_goals: "1",
    start_date: "2024-08-20",
    location: "Stadium A",
  },
  {
    id: "2",
    created_at: "2024-08-13T11:00:00Z",
    home_id: "200",
    away_id: "100",
    season: "2024/25",
    match_type: "2",
    home_goals: "0",
    away_goals: "3",
    start_date: "2024-08-21",
    location: "Stadium B",
  },
  {
    id: "3",
    created_at: "2024-08-13T12:00:00Z",
    home_id: "100",
    away_id: "200",
    season: "2024/25",
    match_type: "2",
    home_goals: "1",
    away_goals: "1",
    start_date: "2024-08-22",
    location: "Stadium C",
  },
  {
    id: "4",
    created_at: "2024-08-13T13:00:00Z",
    home_id: "100",
    away_id: "200",
    season: "2023/24",
    match_type: "1",
    home_goals: "3",
    away_goals: "2",
    start_date: "2023-05-12",
    location: "Stadium D",
  },
  {
    id: "5",
    created_at: "2024-08-13T14:00:00Z",
    home_id: "100",
    away_id: "200",
    season: "2022/23",
    match_type: "1",
    home_goals: "1",
    away_goals: "2",
    start_date: "2022-11-15",
    location: "Stadium E",
  },
];
export const TEAMS: ITeam[] = [
  {
    id: "100",
    team_type: "1",
    team_logo_url: "/assets/logos/Logo.png",
    team_name: "Mazaalai"
  },
  {
    id: "200",
    team_type: "1",
    team_logo_url: "/assets/logos/NashaTech_Logo-03.png",
    team_name: "Nasha"
  },
  {
    id: "300",
    team_type: "2",
    team_logo_url: "/assets/logos/pokka.png",
    team_name: "Pokka"
  },
  {
    id: "400",
    team_type: "2",
    team_logo_url: "/assets/logos/PN.jpg",
    team_name: "PN"
  }
]

export const MONTHS: IMonth[] = [
  { label: 'January 2024', value: '2024-01' },
  { label: 'February 2024', value: '2024-02' },
  { label: 'March 2024', value: '2024-03' },
  { label: 'April 2024', value: '2024-04' },
  { label: 'May 2024', value: '2024-05' },
  { label: 'June 2024', value: '2024-06' },
  { label: 'July 2024', value: '2024-07' },
  { label: 'August 2024', value: '2024-08' },
  { label: 'September 2024', value: '2024-09' },
  { label: 'October 2024', value: '2024-10' },
  { label: 'November 2024', value: '2024-11' },
  { label: 'December 2024', value: '2024-12' },
];